name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Add npm build steps later if you introduce a build (React/Vite/etc.)
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_STUDIO_69644392_9E4F2 }}"
          projectId: "studio-69644392-9e4f2"
          channelId: "live"
